FROM python:3.12-slim

WORKDIR /app

RUN pip install dbt-postgres

COPY maven_toys_dbt/ ./maven_toys_dbt/

WORKDIR /app/maven_toys_dbt

ENV DBT_PROFILES_DIR=/app/maven_toys_dbt

CMD ["sh", "-c", "dbt run && dbt test"]
