version: 2

models:
  - name: fct_sales
    columns: 
      - name: sale_id
        tests: 
          - unique
          - not_null
      - name: store_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_stores')
                field: store_id
      - name: product_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_products')
                field: product_id
  - name: fct_monthly_revenue
    columns:
      - name: sale_month
        tests:
          - unique
          - not_null
  - name: fct_store_performance
    columns:
      - name: store_id
        tests:
          - unique
          - not_null
  - name: fct_product_performance
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
  - name: fct_inventory_risk
    columns: 
      - name: product_id
        tests:
          - unique
          - not_null
      - name: risk_flag
        tests:
          - accepted_values:
              arguments:
                values: ['CRITICAL', 'OK', 'LOW'] 
